### ISSUE TITLE
第13章问题

### ISSUE THREAD

**Issue by huaianlsg88** [waylau/spring-boot-enterprise-application-development#10]
无法显示用户列表

**Comment by waylau** [comment]
debug一下，看是什么错误？

**Comment by huaianlsg88** [comment]
您好，我完全是按照您的代码弄得，275页的效果就是出不来
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Way Lau"<notifications@github.com>;
 发送时间: 2019年3月21日(星期四) 中午12:55
 收件人: "waylau/spring-boot-enterprise-application-development"<spring-boot-enterprise-application-development@noreply.github.com>;
 抄送: "lsg"<1036210491@qq.com>; "Author"<author@noreply.github.com>; 
 主题: Re: [waylau/spring-boot-enterprise-application-development] 第13章问题 (#10)

 

 
debug一下，看是什么错误？

**Comment by waylau** [comment]
可以继续看下后续章节的源码。
后续章节包含了前面几章的源码。

**Comment by huaianlsg88** [comment]
现在就是第13章，第275页的效果出不来，我没有搞清楚users/list.html怎样显示在右侧的，请指教，谢谢




------------------ 原始邮件 ------------------
发件人: "Way Lau"<notifications@github.com>;
发送时间: 2019年3月21日(星期四) 晚上8:38
收件人: "waylau/spring-boot-enterprise-application-development"<spring-boot-enterprise-application-development@noreply.github.com>;
抄送: "lsg"<1036210491@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [waylau/spring-boot-enterprise-application-development] 第13章问题 (#10)




可以继续看下后续章节的源码。
 后续章节包含了前面几章的源码。

**Comment by waylau** [comment]
看这个代码
https://github.com/waylau/spring-boot-enterprise-application-development/blob/master/samples/blog-role/src/main/resources/templates/admins/index.html

里面就定义了左右结构，其中右侧就是你的 users/list.html 里面的内容。
