### ISSUE TITLE
很多地方感觉不匹配

### ISSUE THREAD

**Issue by shiqishidai1** [waylau/spring-boot-enterprise-application-development#11]
我用的idea， add.html里的 <form中 th:object="${userModel.user}" ，userModel.后面就没有user这个选项，自己手写还划红线。

**Comment by shiqishidai1** [comment]
authorities.add(authorityService.getAuthorityById(authorityId)) ;
还有这个 类型也不匹配
![image](https://user-images.githubusercontent.com/48649984/55449745-5013b100-55ff-11e9-878a-f12867d22a54.png)

**Comment by shiqishidai1** [comment]
还有好几个css文件不匹配的问题，明明有，也引入了但是显示拼写错误不生效

**Comment by shiqishidai1** [comment]
Error:(86, 20) java: 对于add(java.util.Optional<com.liu.spring.boot.blog.domain.Authority>), 找不到合适的方法
    方法 java.util.Collection.add(com.liu.spring.boot.blog.domain.Authority)不适用
      (参数不匹配; java.util.Optional<com.liu.spring.boot.blog.domain.Authority>无法转换为com.liu.spring.boot.blog.domain.Authority)
    方法 java.util.List.add(com.liu.spring.boot.blog.domain.Authority)不适用
      (参数不匹配; java.util.Optional<com.liu.spring.boot.blog.domain.Authority>无法转换为com.liu.spring.boot.blog.domain.Authority)

**Comment by waylau** [comment]
@shiqishidai1  换Eclipse 试下，IDE不支持并不代表一定有问题。试下编译有无问题。

**Comment by shiqishidai1** [comment]
编译没问题，主要是公司用的idea，理论上代码是没有问题的，这根用什么工具没太大关系吧，部分css读取不到，这是个主要的问题

**Comment by shiqishidai1** [comment]
我用的idea学习，方便以后的使用，难道说代码根据使用的工具的不同还有不同的书写方式吗？

**Comment by shiqishidai1** [comment]
![image](https://user-images.githubusercontent.com/48649984/55534103-f76b1380-56e5-11e9-9738-2d657219984c.png)
我 这个layout标签一直倒不进去，大概是什么问题啊，不知道怎么解决这问题

**Comment by shiqishidai1** [comment]
![image](https://user-images.githubusercontent.com/48649984/55534154-1cf81d00-56e6-11e9-9d83-fbb58d58698c.png)
我 这个标签一直是灰色导不进去，感觉有问题，大概是哪里出错了？一直没有解决方向

**Comment by waylau** [comment]
@shiqishidai1   编译没有问题，说明代码没有问题。
在IDE里面提示有异常，可能是IDE不支持这个语法，并不代表语法有问题。
只要编译无错即可。
