### ISSUE TITLE
文件服务器搭建问题

### ISSUE THREAD

**Issue by shiqishidai1** [waylau/spring-boot-enterprise-application-development#12]
文件服务器必须单独搭建吗，不能写在项目里吗

**Comment by shiqishidai1** [comment]
我的启动报错
![image](https://user-images.githubusercontent.com/48649984/55784363-020d1a80-5ae3-11e9-96ee-88dc176fad81.png) 这个怎么解决

**Comment by waylau** [comment]
@shiqishidai1  文件服务器是独立的项目。
有关该项目的问题，可以在主页留言  https://github.com/waylau/mongodb-file-server
