### ISSUE TITLE
Thtmeleaf start更新导致的认证失效问题

### ISSUE THREAD

**Issue by xudaye2001** [waylau/spring-boot-enterprise-application-development#15]
**spring-boot-starter-thymeleaf** 引入了**thymeleaf 5**, 所以**书本259页**的依赖应该要改一下:

- 书本上为:

`compile group: 'org.thymeleaf.extras', name: 'thymeleaf-extras-springsecurity4', version: '3.0.2.RELEASE'`

- 更新后为:

`compile group: 'org.thymeleaf.extras', name: 'thymeleaf-extras-springsecurity5', version: '3.0.4.RELEASE'`

**Comment by waylau** [comment]
@xudaye2001 

是版本不兼容引起的。
你的版本，比书中的版本要高。

具体版本，见首页说明 https://github.com/waylau/spring-boot-enterprise-application-development

到时候书本你更新的时候，再做代码的更新。感谢反馈。
