### ISSUE TITLE
GitHub上下载的课程源码"blog-role" 出现报错

### ISSUE THREAD

**Issue by xudaye2001** [waylau/spring-boot-enterprise-application-development#16]
您好, 我在复现书中案例的时候遇到一个问题, 第十三章, 开始我以为是自己代码的问题, 后来我导入GitHub上的课程源码, 也是同样的报错.
问题出现在书本第270页 修改userController的postMapping方法上.
 ```
@PostMapping
    public ResponseEntity<Response> saveOrUpdateUser(User user, Long authorityId) {
		List<Authority> authorities = new ArrayList<>();
		authorities.add(authorityService.getAuthorityById(authorityId));	//这里会报错in List cannot be applied
		user.setAuthorities(authorities);

        try {
            userService.saveOrUpateUser(user);
        } catch (ConstraintViolationException e)  {
            return ResponseEntity.ok().body(new Response(false, ConstraintViolationExceptionHandler.getMessage(e)));
        }
        return ResponseEntity.ok().body(new Response(true, "处理成功", user));
    }
```

**Comment by xudaye2001** [comment]
问题貌似解决了, 书本上的
`authorities.add(authorityService.getAuthorityById(authorityId));`
更改为:
`authorities.add(authorityService.getAuthorityById(authorityId).get());`

**Comment by waylau** [comment]
@xudaye2001  你IDE的JDK版本是否太低了？设置为JDK 8及以上试下

**Comment by xudaye2001** [comment]
`authorities.add(authorityService.getAuthorityById(authorityId))`
改为:
`authorities.add(authorityService.getAuthorityById(authorityId)).get()`
书本里面有几个地方都漏了.get()返回对象

**Comment by waylau** [comment]
@xudaye2001  你是spring security版本是多少？

**Comment by xudaye2001** [comment]
依赖直接填的   
` implementation 'org.springframework.boot:spring-boot-starter-security'`
看了下包的版本是:`5.2.1`

**Comment by xudaye2001** [comment]
然后thymeleaf 也要改为   ` compile group: 'org.thymeleaf.extras', name: 'thymeleaf-extras-springsecurity**5**', version: '3.0.4.RELEASE'`

**Comment by xudaye2001** [comment]
然后thymeleaf也要改为:
    `compile group: 'org.thymeleaf.extras', name: 'thymeleaf-extras-springsecurity5', version: '3.0.4.RELEASE'`
4不支持

**Comment by waylau** [comment]
@xudaye2001  是版本不兼容引起的。
你的版本，比书中的版本要高。


具体版本，见首页说明  https://github.com/waylau/spring-boot-enterprise-application-development
